version: '3.8'

services:
  eureka-server:
    container_name: eureka
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  association-app:
    container_name: association-app
    build:
      context: ./Association
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    depends_on:
      - eureka-server
      - mysqldb
    ports:
      - "8791:8791"
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
