version: "3.9"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  service-registration:
    hostname: registration
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      stdin_open: true
      tty: true
    build: /server
    restart: on-failure
    ports:
      - "8761:8761"
    image: "service-registration"

  job:
    env_file: ./.env
    build: /job
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://service-registration:8761/eureka
    ports:
      - "8791:8791"
    depends_on:
      - service-registration
    links:
      - service-registration
volumes:
  db: